services:
  db:
    image: "postgres:16.1-alpine"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./.data:/var/lib/postgresql/data
